### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by yotkadata** [bundestag/NamedPollDeputies#2]
Hi,

this is a great resource, thanks a lot! Will it be updated to include the latest votes?

Best
yan

**Comment by ulfgebhardt** [comment]
I think democracy made an update using the api of Bundestag and therefore stopped this service. For more info ask them

**Comment by yotkadata** [comment]
Thanks. It seems the Bundestag API (https://dip.bundestag.de/%C3%BCber-dip/hilfe/api) doesn't include named polls (namentliche Abstimmungen), but at least there are Excel lists. I'll see if I can work with them.
